steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/federation-workshop/summit-router-final', './router']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/federation-workshop/summit-router-final']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'summit-router-final', '--image', 'gcr.io/federation-workshop/summit-router-final','--allow-unauthenticated', 
    '--region', 'us-east1', '--update-env-vars', 'APOLLO_KEY=${_APOLLO_KEY},APOLLO_GRAPH_REF=${_APOLLO_GRAPH_REF}']
images:
- gcr.io/federation-workshop/summit-router-final
