name: Deploy Website to Cloud Run

on:
    push:
        paths:
          - website/**

env:
  GEN: "workshop"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - id: "auth"
      uses: "google-github-actions/auth@v0"
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker

    - name: Build Website Docker image
      run: |
        docker build -t gcr.io/summit-enterprise-workshop/${{github.actor}}-website:latest .
        docker images
      working-directory: ./website

    - name: Push Docker image to Google Container Registry
      run: |
        docker push gcr.io/summit-enterprise-workshop/${{github.actor}}-website:latest
      working-directory: ./website

    - name: Deploy Website to Cloud Run
      run: |
        gcloud run deploy ${{github.actor}}-orders \
          --image gcr.io/summit-enterprise-workshop/${{github.actor}}-website:latest \
          --platform managed \
          --region us-central1 \
          --update-env-vars APOLLO_KEY=${{ secrets.APOLLO_KEY }},APOLLO_GRAPH_REF=${{ secrets.APOLLO_GRAPH_REF }} \
          --allow-unauthenticated
    - name: Get URL
      run: | 
        gcloud run services describe ${{vars.ACTOR}}-website --region us-central1 --format 'value(status.url)' > url.json
            echo "::notice URL=$(cat url.json)"
